---
- name: Install Ruby/Rails dependencies packages
  yum:
    name:
      - gcc-c++
      - glibc-headers
      - openssl-devel
      - readline
      - libyaml-devel
      - readline-devel
      - zlib
      - zlib-devel
      - libffi-devel
      - libxml2
      - libxslt
      - libxml2-devel
      - libxslt-devel
      - sqlite-devel
      - libxml2-devel
      - ImageMagick
      - ImageMagick-devel
    state: present

- name: Install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: "{{ rbenv_root }}"

- name: Edit bashrc
  template:
    src: roles/ruby/templates/rbenv_system.sh.j2
    dest: /etc/profile.d/rbenv.sh
    owner: ec2-user
    group: ec2-user

- name: Install ruby-build
  git:
    repo: "{{ ruby_build_download_url }}"
    dest: "{{ rbenv_root }}/plugins/ruby-build"

- name: Install Ruby
  shell: bash -lc " rbenv install -s {{ ruby_version }}"

- name: Set default Ruby version
  shell: bash -lc "rbenv global {{ ruby_version }} && rbenv rehash"

- name: Install rbenv-rehash, bundler and rails
  shell: bash -lc "gem install {{ item }}"
  with_items:
    - rbenv-rehash
    - bundler:{{ bundler_version }}
    - rails -v {{ rails_version }}