AWSTemplateFormatVersion: 2010-09-09
Description: RaiseTech lecture10 template for RDS

Parameters:
  VPCStack:
    Type: String
    Default: lecture10-VPC
  DBUser:
    Type: String
    Default: KentaroOmori
  DBPassword:
    Type: String
    Default: 1234ABCD%%%%
    NoEcho: true

# RDSの構築

Resources:
  CFnRDS:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "10"
      StorageType: gp2
      Engine: MySQL
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBName: wordpress
      BackupRetentionPeriod: 0
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      Tags:
        - Key: Name
          Value: lecture10-cfn-RDS

# Subnetグループの作成

  DBSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: DB Subnet Group for Private Subnet
      SubnetIds: 
        - Fn::ImportValue: !Sub ${VPCStack}-PrivateSubnetA
        - Fn::ImportValue: !Sub ${VPCStack}-PrivateSubnetC

# セキュリティグループで3306ポートのインバウンドを許可

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: !Sub ${AWS::StackName}-MySQL
      VpcId:
        Fn::ImportValue: !Sub ${VPCStack}-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16


Outputs:
  DBEndpoint:
    Value: !GetAtt CFnRDS.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-DBEndpoint
