---
- name: Install Rails dependencies packages
  yum:
    name:
      - libxml2-devel
      - ImageMagick
      - ImageMagick-devel
    state: present

- name: Change directory and bundle install
  command:
    cmd: bash -lc "bundle install"
    chdir: "/var/www/{{ app_name }}"

- name: Start nginxd
  become: yes
  shell: bash -lc "systemctl start nginx.service"  

- name: Set database
  block:
  - name: Create database
    command:
      cmd: bash -lc "bundle exec rails db:create"
      chdir: "/var/www/{{ app_name }}"
    environment:
      RAILS_ENV: production
  - name: Migrate database
    command:
      cmd: bash -lc "bundle exec rails db:migrate"
      chdir: "/var/www/{{ app_name }}"
    environment:
      RAILS_ENV: production

- name: Create config/unicorn.rb
    template:
    src: roles/start_app/templates/unicorn.rb.j2
    dest: "/var/www/{{ app_name }}/config/unicorn.rb"
    owner: ec2-user
    group: ec2-user

- name: Start unicorn
  command:
    cmd: bash -lc "bundle exec unicorn_rails -c "/var/www/{{ app_name }}/config/unicorn.rb" -D -E production"
    chdir: "/var/www/{{ app_name }}"
