---
- name: Install Rails dependencies packages
  yum:
    name:
      - libxml2-devel
      - ImageMagick
      - ImageMagick-devel
    state: present

- name: Change directory and bundle install
  command:
    cmd: bash -lc "bundle install"
    chdir: "/var/www/{{ app_name }}"

- name: Check if masterkey exists
  stat:
    path: "/var/www/{{ app_name }}/config/master.key"
  register: masterkey_stat

- name: Set master.key
  block: 
    - name: Touch master.key
      file:
        path: "/var/www/{{ app_name }}/config/master.key"
        state: touch
    - name: Edit master.key
      vars:
        master_key: "{{ lookup('env', 'rails_master_key') }}"
      lineinfile:
        path: "/var/www/{{ app_name }}/config/master.key"
        insertafter: EOF
        line: "{{ master_key }}"
  when: not masterkey_stat.stat.exists

- name: Install webpacker
  become: yes
  expect:
    command:
      cmd: bash -lc "bundle exec rails webpacker:install"
      chdir: "/var/www/{{ app_name }}"
    environment:
      RAILS_ENV: production  
    responses:
      (.*)Overwrite (.*)Gemfile(.*): "n"

- name: Start nginxd
  become: yes
  shell: bash -lc "systemctl start nginx.service"  

- name: Set database
  block:
  - name: Create database
    command:
      cmd: bash -lc "bundle exec rails db:create"
      chdir: "/var/www/{{ app_name }}"
    environment:
      RAILS_ENV: production
  - name: Migrate database
    command:
      cmd: bash -lc "bundle exec rails db:migrate"
      chdir: "/var/www/{{ app_name }}"
    environment:
      RAILS_ENV: production

- name: Create config/unicorn.rb
  template:
    src: roles/start_app/templates/unicorn.rb.j2
    dest: "/var/www/{{ app_name }}/config/unicorn.rb"
    owner: ec2-user
    group: ec2-user

# - name: Check unicorn status


- name: Start unicorn
  command:
    cmd: bash -lc "bundle exec unicorn_rails -c '/var/www/{{ app_name }}/config/unicorn.rb' -D -E production"
    chdir: "/var/www/{{ app_name }}"
