---
- name:  Git Clone directory created
  become: yes
  file:
    path: /var/www/raisetech-live8-sample-app
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "775"

- name: Clone the repository
  git:
    repo: "{{ git_repo }}"
    dest: "{{ clone_dest }}"
