---
- name:  Git Clone directory created
  file:
    path: /var/www
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "775"

- name: Clone the repository
  # shell: bash -lc "git clone {{ git_repo }} {{ clone_dest }}"
  git:
    repo: "{{ git_repo }}"
    dest: "{{ clone_dest }}"
