---
- name: Registration nodejs on Yum repo
  shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | sudo bash -
  when: not ansible_check_mode

- name: Install nodejs from yum
  yum:
    name: nodejs
    state: installed
  ignore_errors: "{{ ansible_check_mode }}" # dry-run時のエラーを無視

- name: Install yarn
  npm:
    name: yarn
    global: yes
    state: present