---
- name: Install the prerequisites
  yum:
    name: yum-utils
    state: present

- name: Create Nginx repo
  template:
    src: roles/nginx/templates/nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
  when: not ansible_check_mode

- name: Install Nginx
  become: yes
  yum:
    name: nginx
  ignore_errors: "{{ ansible_check_mode }}" # dry-run時のエラーを無視

- name: Set nginx conf.d
  template:
    src: roles/nginx/templates/nginx_conf.d.j2
    dest: /etc/nginx/conf.d/sample.conf
  
- name: remove default.conf
  become: yes
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent