---
- hosts: web
  become: yes
  tasks:
  - name: ls
    shell: ls
    register: result_ls
  - name: result_ls
    debug:
      msg: "{{ result_ls.stdout }}"
  - name: installed git
    yum:
      name: git
      state: installed