---
- hosts: web
  become: yes
  roles:
    - { role: git, tags: git }
    - { role: nodejs, tags: nodejs }
    - { role: nginx, tags: nginx }
    - { role: ruby, tags: ruby }
    - { role: mysql, tags: mysql}
    - { role: git_clone, tags: git_clone}
    - { role: start_app, tags: start_app}